
#- name: SetupAdd an environment variable crontab entry to call the script.
- cron:
    name: MOTHERSHIP_PING_URL
    env: yes
    value: http://192.168.1.80:8080/beto-land-network/ping/register

- name: Copy the BASH script that pings the mothership.
  copy:
    src: ping-mothership.sh
    dest: /opt/onebeartoe/
    mode: u+rwx

#- name: Add a crontab entry to call the script.
- cron:
    name: "ping-mothership"
    minute: "*/2"
    job: "/opt/onebeartoe/ping-mothership.sh"
