
- name: Copy the BASH script that pings the mothership.
  copy:
    src: ping-mothership.sh
    dest: /opt/onebeartoe/
    mode: u+rwx
    
- name: test the sript.
  shell: /opt/onebeartoe/ping-mothership.sh
