

- shell: |
    cd /opt/onebeartoe
    pwd
    ls -la
    reboot
  register: stdout_lines


- name: debug output
  debug: msg={{ stdout_lines.stdout.split('\n') }}


# It seem the built-in 'reboot' is in newer versions of Ansible than the one used
# in this project.
#- name: Unconditionally reboot the machine with all defaults.
#  reboot: