
pipeline 
{
    agent
    {
        label 'master'
    }

    stages 
    {
        stage('Install Java 11')
        {
            steps
            {
                
                echo 'Installing Java 11...'

                sh '''
                    ansible-playbook --version

                    pwd

                    ls -ltrh

                    cd src/main/ansible/

                    cp ${ansible_inventory_path} .

                    ls -ltrh

                    # This script/Ansible expects to work with Python 2.7.12
                    # -i is the path inventory file; -l is the limit for the groups in the inventory file
                    ansible-playbook playbooks/package-manager/java/openjdk-11.yml -i ansible-betoland.inventory -l ${hostLimit}
                '''
            }
        }
    }
}
