
pipeline 
{
    agent
    {
        label 'master'
    }

    stages 
    {
        stage('reboot host')
        {
            steps
            {                
                echo 'rebooting host...'

                sh '''
                    pwd

                    cd src/main/ansible/

                    cp ${ansible_inventory_path} .

# add -v to the end of the next line if the output does not show up
                    ansible-playbook playbooks/reboot.yml -i ansible-betoland.inventory -l ${hostLimit}
                '''
            }
        }
    }
}
