

pipeline 
{
    agent
    {
        label 'master'
    }

    stages 
    {
        stage('Update Package Managers')
        {
            steps
            {
                
                echo 'Updating package managers...'

                sh '''
                    pwd

                    ls -ltrh

                    cd src/main/ansible/

                    cp ${ansible_inventory_path} .

                    ls -ltrh

#                    ansible-playbook start-neje-engrave.yml -i ansible-betoland.inventory -l laserengraver1
                '''
            }
        }
    }
}
