
- hosts: all
  gather_facts: yes
  serial: 1
  become: true
  tasks:
  - name: Real Distribution
    debug: msg="the distro is -> {{ ansible_distribution }}"  
  roles:
    - ../../../roles/package-manager/java/openjdk-9

