---

- hosts: all
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    package:
      name: jdk9-openjdk
      state: present
    when: ansible_lsb['description'] is defined and ansible_lsb['description'] == "Manjaro Linux"

  - name: install apache and php for CentOS servers
    package:
      name: openjdk-9-jdk
      state: present
    when: ansible_distribution is defined and ansible_distribution == "Ubuntu"
