
pipeline 
{
    agent
    {
        label 'master'
    }

    stages 
    {
        stage('Show Freespace')
        {
            steps
            {
                
                echo 'Show Freespace...'

                sh '''
                    ansible-playbook --version

                    pwd

                    ls -ltrh

                    cd src/main/ansible/

                    cp ${ansible_inventory_path} .

                    ls -ltrh

                    ansible-playbook playbooks/free-status.yml -i ansible-betoland.inventory -l all -v
                '''
            }
        }
    }
}

