
- name: Copy the Groovy script.
  copy:
    src: RevertConfiguration.groovy
    dest: /opt/onebeartoe/octoprint/
    mode: a+rwx

- shell: JAVA_HOME=/usr groovy /opt/onebeartoe/octoprint/RevertConfiguration.groovy
