
- name: Copy the Groovy script.
  copy:
    src: RevertConfiguration.groovy
    dest: /opt/onebeartoe/octoprint/
    mode: a+rwx

- shell: cd /opt/onebeartoe/octoprint/; JAVA_HOME=/usr groovy RevertConfiguration.groovy
