
# thanks for the awk help, 7winkie
#       https://stackoverflow.com/a/7918051/803890

- shell: |
    cd ~/.octoprint/uploads/
    pwd
    find . -type f -name "*.gcode" -printf "%T@ %Tc %p\n" | sort -n | awk '{for (i=2; i<=NF; i++) print $i}'
  register: stdout_lines

#- shell: cd ~/.octoprint/uploads/; pwd; cat outfile.text

- name: debug output
  debug: msg={{ stdout_lines.stdout.split('\n') }}