
#- shell: |
#    pwd
#    echo $HOSTNAME

#- shell: JAVA_HOME=/usr groovy -version 

#- shell: JAVA_HOME=/usr groovy Configuration.groovy

#---------------------------------------

- name: Copy the Groovy script.
  copy:
    src: Configuration.groovy
    dest: /opt/onebeartoe/octoprint/
    mode: a+rwx
    
- name: Copy the Groovy PATHS script.
  copy:
    src: ConfigurationPaths.groovy
    dest: /opt/onebeartoe/octoprint/
    mode: a+rwx

- shell: JAVA_HOME=/usr groovy /opt/onebeartoe/octoprint/Configuration.groovy

#---------------------------------------

#- script: Configuration.sh
#- script: roles/octoprint/email-notifications/configuration/Configuration.sh
    
#- shell: |
#    export JAVA_HOME=/usr 
#    groovy roles/octoprint/email-notifications/configuration/Configuration.groovy
    