
- shell: |
    pwd
    echo $HOSTNAME

- shell: JAVA_HOME=/usr groovy -version 

- shell: |
    export JAVA_HOME=/usr 
    groovy roles/octoprint/email-notifications/configuration/Configuration.groovy