
- shell: |
    pwd
    echo $HOSTNAME

- shell: JAVA_HOME=/usr groovy -version 

#- shell: JAVA_HOME=/usr groovy Configuration.groovy

- script: Configuration.sh
#- script: roles/octoprint/email-notifications/configuration/Configuration.sh
    
#- shell: |
#    export JAVA_HOME=/usr 
#    groovy roles/octoprint/email-notifications/configuration/Configuration.groovy
    