
- name: Copy the Groovy script.
  copy:
    src: Configuration.groovy
    dest: /opt/onebeartoe/octoprint/
    mode: a+rwx

- name: Copy the Octoprint Events configuration.
  copy:
    src: config.xml.events
    dest: /opt/onebeartoe/octoprint/
    mode: a+rwx
    
- name: Copy a sample SMTP configuration file.
  copy:
    force: no
    src: smtp.properties
    dest: /opt/onebeartoe/octoprint/
    mode: a+rwx

- shell: cd /opt/onebeartoe/octoprint/; JAVA_HOME=/usr groovy Configuration.groovy
    